name: Pull request

on: pull_request

jobs:
  linting:
    name: Code style checks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: .tool-versions

      - name: Install npm dependencies
        shell: bash
        run: npm install

      - name: Install poetry
        run: pipx install poetry

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: '.tool-versions'
          cache: poetry

      - name: Install python depdenencies
        run: poetry install

      - name: Run linting
        run: npm run lint

  regression:
    name: Visual regression tests
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: .tool-versions

      - name: Install npm dependencies
        shell: bash
        run: npm install

      - name: Setup Playwright
        run: npm run postinstall
        
      - name: Install poetry
        run: pipx install poetry

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: '.tool-versions'
          cache: poetry

      - name: Install python depdenencies
        run: poetry install

      - name: Run backstop
        run: npm run test:visual --ignore-scripts

      - name: Save backstop report
        if: ${{ !cancelled() }}
        uses: actions/upload-artifact@v4
        with:
          name: Backstop report
          path: tests/backstop/
          if-no-files-found: ignore